export const LEVEL_CATEGORY = {
  categoryType: "levelCategory",
  title: "Filter by specialist level",
  data: ["Student", "Junior", "Mid level", "Senior", "C level", "Not defined"],
};

export const JOB__CATEGORY = {
  categoryType: "jobCategory",
  title: "Filter by job category",
  data: [
    "Software development",
    "Quality Assurance /Control",
    " UI/UX/Graphic Design",
    " Product/Project Management",
    "Hardware design",
    "Other IT",
    "Sales/service management",
    "Administrative/office-work",
    "Tourism/Hospitality/HoReCa",
    "Marketing/Advertising",
    "Communications/Journalism/PR",
    " Accounting/Bookkeeping/Cash register",
    " Finance Management",
    "Banking/credit",
    "TV/Radio",
    "Education/training",
    " Legal",
    " Audit/Compliance",
    "Healthcare/Pharmaceuticalt",
    "Construction",
    "Human Resources",
    "Sports/Beauty",
    "Procurement/Logistics/Courier",
    "Production/Bookkeeping/Cash register",
    "Business/Management",
    "Art/Design/Architecture",
    " General/professional/Other services",
    "IT security/Networks",
    " NGO/Nonprofit",
    "Insurance",
    "Entertainment",
    "Data Science/Data Engineering",
    " Foreign language",
    "Hardware Design",
    " Data Research/Analysis",
    " Mechanical/Engineering",
    "System Admin/Engineer",
    " Network Administratio",
    "Consultancys",
    "State/ Public/ Civil servic",
    "Science",
    "Content writing",
    "Security",
    "DevOps/Infrastructure",
    "IT Support/Technician",
  ],
};
export const CITIES = {
  title: " Filter by job cities",
  categoryType: "jobCities",
  data: [
    "Yerevan",
    "Gyumri",
    "Vanadzor",
    "Abovyan",
    "Akhuryan",
    "Alaverdi",
    "Amasia",
    "Aparan",
    "Armavir",
    "Armenia (All cities)",
    "Artashat",
    "Artik",
    "Arzni",
    "Ashtarak",
    "Baghramyan",
    "Berd",
    "Berlin",
    "Dilijan",
    "Dubai",
    "Emmen",
    "Fresno",
  ],
};
export const LEVEL__CATEGORY__COMPANY = {
  categoryType: "activTypeCategoryCompany",
  title: "Filter by activity type",
  data: ["Employer", "Training"],
};

export const JOB_TYPE = {
  data: ["Full time", "Part time", "Remote", "Flexible schedule"],
};

export const COMPANY__INDUSTRIES = {
  categoryType: "industryCategoryCompany",

  title: "Filter by industry",
  data: [
    "Finance/Banking/Insurance ",
    "Information technologies",
    "Design/Architecture/Construction",
    "Human Resources/Consulting/ Legal",
    "Import/Export/Trade",
    "Marketing/Advertising/PR",
    "Tourism/Hospitality/Entertainment",
    "Medical/Pharmaceutical ",
    "Sports /Beauty",
    "Mining/Manufacturing/Production",
    "TV/Radio/Media",
    "Education ",
    "Telecommunications",
    "Services",
    "NGO/International organization",
    "Government",
    "Agriculture/Winemaking",
    "Logistics/Courier",
    "Foundation",
    "Sport/Betting",
    "Appliance store",
    "Retail business",
    "Online Service",
    "Municipality / State",
    "e-Commerce",
    "Investment management",
    "Aviation",
  ],
};
