export const COUNTRIES = ["USA", "ARMENIA", "RUSSIA"];
export const CITIES = [
  "Yerevan",
  "Gyumri",
  "Vanadzor",
  "Abovyan",
  "Akhuryan",
  "Alaverdi",
  "Amasia",
  "Aparan",
  "Armavir",
  "Armenia (All cities)",
  "Artashat",
  "Artik",
  "Arzni",
  "Ashtarak",
  "Berd",
  "Berlin",
  "Dilijan",
  "Dubai",
];

export const SPECIALIST_LEVELS = {
  title: "Filter by specialist level",
  categories: "specialistLevel",
  levels: [
    "Student",
    "Junior",
    "Mid level",
    "Senior",
    "C level",
    "Not defined",
  ],
};

export const ACTIVITY_TYPE_LEVELS = {
  title: "Filter by activity type",
  categories: "activityType",
  levels: ["Employer", "Training provider"],
};

export const JOB_CATEGORY_LEVELS = {
  title: "Filter by job category",
  categories: "jobCategory",
  levels: [
    "Software development",
    "Quality Assurance /Control",
    " UI/UX/Graphic Design",
    "Product/Project Management",
    "Hardware design",
    "Other IT",
    "Sales/service management",
    "Administrative/office-work",
    "Tourism/Hospitality/HoReCa",
    "Marketing/Advertising",
    "Communications/Journalism/PR",
    "Accounting/Bookkeeping/Cash register",
    "Finance Management",
    "Banking/credit",
    "TV/Radio",
    "Education/training",
    "Legal",
    "Audit/Compliance",
    "Healthcare/Pharmaceuticalt",
    "Construction",
    "Human Resources",
    "Sports/Beauty",
    "Procurement/Logistics/Courier",
    "Production/Bookkeeping/Cash register",
    "Business/Management",
    "Art/Design/Architecture",
    "General/professional/Other services",
    "IT security/Networks",
    "NGO/Nonprofit",
    "Insurance",
    "Entertainment",
    "Data Science/Data Engineering",
    "Foreign language",
    "Hardware Design",
    "Data Research/Analysis",
    "Mechanical/Engineering",
    "System Admin/Engineer",
    "Network Administratio",
    "Consultancys",
    "State/ Public/ Civil servic",
    "Science",
    "Content writing",
    "Security",
    "DevOps/Infrastructure",
    "IT Support/Technician",
  ],
};

export const INDUSTRIES_LEVELS = [
  "Finance/Banking/Insurance ",
  "Information technologies",
  "Design/Architecture/Construction",
  "Human Resources/Consulting/ Legal",
  "Import/Export/Trade",
  "Marketing/Advertising/PR",
  "Tourism/Hospitality/Entertainment",
  "Medical/Pharmaceutical ",
  "Sports /Beauty",
  "Mining/Manufacturing/Production",
  "TV/Radio/Media",
  "Education ",
  "Telecommunications",
  "Services",
  "NGO/International organization",
  "Government",
  "Agriculture/Winemaking",
  "Logistics/Courier",
  "Foundation",
  "Sport/Betting",
  "Appliance store",
  "Retail business",
  "Online Service",
  "Municipality / State",
  "e-Commerce",
  "Investment management",
  "Aviation",
];
